name: Coverage

on:
  push:
    branches: [master]
  pull_request:

jobs:
  coverage:
    name: Run coverage and upload to Codecov
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - run: aria2c -i links.txt
        working-directory: samples

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@305bebabd4457bed9b82541755f034994382465b
        with:
          tool: cargo-llvm-cov

      - name: Download dependencies
        run: cargo fetch
        shell: bash

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json

      - name: Upload coverage data to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          files: codecov.json
          use_oidc: true
